---
title: "Exploration"
output: html_notebook
---

```{r setup}
library(tidyverse)
knitr::opts_chunk$set(paged.print=FALSE)
library(tidytext)
library(topicmodels)
```

```{r}
papers <- read_tsv("../data/tidy/papers.tsv")
```


# Abstract


```{r}
abstract_word_counts <- unnest_tokens(select(papers, title, abstract),
                                      word, abstract) %>% 
    anti_join(get_stopwords()) %>% 
    count(title, word)
head(abstract_word_counts)
```

```{r}
abstract_dtm <- abstract_word_counts %>% 
    cast_dtm(title, word, n)
abstract_dtm
```

```{r}
abstract_lda <- LDA(abstract_dtm, k = 10)
abstract_lda
```

```{r}
abstract_topics <- tidy(abstract_lda, matrix = "beta")
abstract_topics
```

```{r}
main_words <- abstract_topics %>% 
    group_by(topic) %>% 
    top_n(n = 10, wt = beta) %>% 
    ungroup() %>% 
    arrange(topic, -beta) %>% 
    group_by(topic) %>% 
    mutate(rank = str_c("word_", row_number())) %>%
    select(topic, rank, term) %>%
    pivot_wider(names_from = rank, values_from = term)
main_words
```

```{r}
abstract_documents <- tidy(abstract_lda, matrix = "gamma")
abstract_documents
```
```{r}
abstract_documents %>% filter(topic == 3 & gamma > 0.5) %>% arrange(-gamma)
```

```{r}
abstract_documents %>% 
    mutate(main = gamma > 0.5) %>% 
    group_by(topic) %>% 
    summarize(main = sum(main)) %>% 
    arrange(-main) %>% 
  left_join(main_words)
```


# Full text


```{r eval=FALSE, include=FALSE}
text_word_counts <- unnest_tokens(select(papers, title, text),
                                      word, text) %>% 
    anti_join(get_stopwords()) %>% 
    count(title, word)
head(text_word_counts)
```

```{r eval=FALSE, include=FALSE}
text_dtm <- text_word_counts %>% 
    cast_dtm(title, word, n)
text_dtm
```

```{r eval=FALSE, include=FALSE}
text_lda <- LDA(text_dtm, k = 10)
text_lda
```

```{r eval=FALSE, include=FALSE}
text_topics <- tidy(text_lda, matrix = "beta")
text_topics
```

```{r eval=FALSE, include=FALSE}
main_words <- text_topics %>% 
    group_by(topic) %>% 
    top_n(n = 10, wt = beta) %>% 
    ungroup() %>% 
    arrange(topic, -beta) %>% 
    group_by(topic) %>% 
    mutate(rank = str_c("word_", row_number())) %>%
    select(topic, rank, term) %>%
    pivot_wider(names_from = rank, values_from = term)
main_words
```

```{r eval=FALSE, include=FALSE}
text_documents <- tidy(text_lda, matrix = "gamma")
text_documents
```

```{r eval=FALSE, include=FALSE}
text_documents %>% filter(topic == 3 & gamma > 0.5) %>% arrange(-gamma)
```

```{r eval=FALSE, include=FALSE}
text_documents %>% 
    mutate(main = gamma > 0.5) %>% 
    group_by(topic) %>% 
    summarize(main = sum(main)) %>% 
    arrange(-main) %>% 
  left_join(main_words)
```

